@ApiDemo_HostAddress = http://localhost:5000

POST {{ApiDemo_HostAddress}}/shirts/
content-type: application/json

{
    "brand": "Adidas",
    "color": "White",
    "size": 13,
    "gender": "Men",
    "price": 33
    }